### ISSUE TITLE
Build error against v14

### ISSUE THREAD

**Issue by devrimgunduz** [anayrat/pg_sampletolog#3]
Hi,

2.0.0 fails to build against v14. Log is below. Can you please take a look? v14 is around the corner. Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_sampletolog.o pg_sampletolog.c
/usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pg_sampletolog.bc pg_sampletolog.c
pg_sampletolog.c: In function '_PG_init':
pg_sampletolog.c:223:37: warning: assignment to 'ProcessUtility_hook_type' {aka 'void (*)(PlannedStmt *, const char *, _Bool,  ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, QueryCompletion *)'} from incompatible pointer type 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, DestReceiver *, char *)' {aka 'void (*)(PlannedStmt *, const char *, ProcessUtilityContext,  struct ParamListInfoData *, QueryEnvironment *, struct _DestReceiver *, char *)'} [-Wincompatible-pointer-types]
  223 |                 ProcessUtility_hook = pgsl_ProcessUtility;
      |                                     ^
pg_sampletolog.c: In function 'pgsl_ProcessUtility':
pg_sampletolog.c:385:65: error: incompatible type for argument 4 of 'prev_ProcessUtility'
  385 |                                                                 params,
      |                                                                 ^~~~~~
      |                                                                 |
      |                                                                 ParamListInfo {aka struct ParamListInfoData *}
pg_sampletolog.c:385:65: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
pg_sampletolog.c:387:65: warning: passing argument 5 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  387 |                                                                 queryEnv,
      |                                                                 ^~~~~~~~
      |                                                                 |
      |                                                                 QueryEnvironment *
pg_sampletolog.c:387:65: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
pg_sampletolog.c:389:65: warning: passing argument 6 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  389 |                                                                 dest, completionTag);
      |                                                                 ^~~~
      |                                                                 |
      |                                                                 DestReceiver * {aka struct _DestReceiver *}
pg_sampletolog.c:389:65: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
pg_sampletolog.c:389:71: warning: passing argument 7 of 'prev_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  389 |                                                                 dest, completionTag);
      |                                                                       ^~~~~~~~~~~~~
      |                                                                       |
      |                                                                       char *
pg_sampletolog.c:389:71: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'char *'
pg_sampletolog.c:377:18: error: too few arguments to function 'prev_ProcessUtility'
  377 |                 (*prev_ProcessUtility) (
      |                 ~^~~~~~~~~~~~~~~~~~~~~
pg_sampletolog.c:399:65: error: incompatible type for argument 4 of 'standard_ProcessUtility'
  399 |                                                                 params,
      |                                                                 ^~~~~~
      |                                                                 |
      |                                                                 ParamListInfo {aka struct ParamListInfoData *}
In file included from pg_sampletolog.c:21:
/usr/pgsql-14/include/server/tcop/utility.h:87:95: note: expected 'ProcessUtilityContext' but argument is of type 'ParamListInfo' {aka 'struct ParamListInfoData *'}
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
pg_sampletolog.c:401:65: warning: passing argument 5 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  401 |                                                                 queryEnv,
      |                                                                 ^~~~~~~~
      |                                                                 |
      |                                                                 QueryEnvironment *
In file included from pg_sampletolog.c:21:
/usr/pgsql-14/include/server/tcop/utility.h:87:118: note: expected 'ParamListInfo' {aka 'struct ParamListInfoData *'} but argument is of type 'QueryEnvironment *'
   87 |                                                                         ProcessUtilityContext context, ParamListInfo params,
      |                                                                                                        ~~~~~~~~~~~~~~^~~~~~
pg_sampletolog.c:403:65: warning: passing argument 6 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  403 |                                                                 dest, completionTag);
      |                                                                 ^~~~
      |                                                                 |
      |                                                                 DestReceiver * {aka struct _DestReceiver *}
In file included from pg_sampletolog.c:21:
/usr/pgsql-14/include/server/tcop/utility.h:88:91: note: expected 'QueryEnvironment *' but argument is of type 'DestReceiver *' {aka 'struct _DestReceiver *'}
   88 |                                                                         QueryEnvironment *queryEnv,
      |                                                                         ~~~~~~~~~~~~~~~~~~^~~~~~~~
pg_sampletolog.c:403:71: warning: passing argument 7 of 'standard_ProcessUtility' from incompatible pointer type [-Wincompatible-pointer-types]
  403 |                                                                 dest, completionTag);
      |                                                                       ^~~~~~~~~~~~~
      |                                                                       |
      |                                                                       char *
In file included from pg_sampletolog.c:21:
/usr/pgsql-14/include/server/tcop/utility.h:89:87: note: expected 'DestReceiver *' {aka 'struct _DestReceiver *'} but argument is of type 'char *'
   89 |                                                                         DestReceiver *dest, QueryCompletion *qc);
      |                                                                         ~~~~~~~~~~~~~~^~~~
pg_sampletolog.c:391:17: error: too few arguments to function 'standard_ProcessUtility'
  391 |                 standard_ProcessUtility(
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from pg_sampletolog.c:21:
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: declared here
   85 | extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pg_sampletolog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_sampletolog.c:223:23: warning: incompatible function pointer types assigning to 'ProcessUtility_hook_type' (aka 'void (*)(struct PlannedStmt *, const char *, bool, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, struct QueryCompletion *)') from 'void (PlannedStmt *, const char *, ProcessUtilityContext, ParamListInfo, QueryEnvironment *, DestReceiver *, char *)' (aka 'void (struct PlannedStmt *, const char *, ProcessUtilityContext, struct ParamListInfoData *, struct QueryEnvironment *, struct _DestReceiver *, char *)') [-Wincompatible-function-pointer-types]
                ProcessUtility_hook = pgsl_ProcessUtility;
                                    ^ ~~~~~~~~~~~~~~~~~~~
pg_sampletolog.c:389:28: error: too few arguments to function call, expected 8, have 7
                                                                dest, completionTag);
                                                                                   ^
pg_sampletolog.c:403:28: error: too few arguments to function call, expected 8, have 7
                                                                dest, completionTag);
                                                                                   ^
/usr/pgsql-14/include/server/tcop/utility.h:85:13: note: 'standard_ProcessUtility' declared here
extern void standard_ProcessUtility(PlannedStmt *pstmt, const char *queryString,
            ^

**Comment by anayrat** [comment]
Hello @devrimgunduz 

Thanks for your attention. But, as the main goal of this extension is to log a sample of statement in logs. All these features have been added into core since postgres 12 and 13, I do not think it is worth to keep the compatibility for future Postgres versions.

Is it ok for you?

Thanks

**Comment by devrimgunduz** [comment]
Hi @anayrat ,

Sure, that is good to know. Thanks a lot!
