### ISSUE TITLE
Support for PostgreSQL 16 (and 15, 14 and 13)

### ISSUE THREAD

**Issue by devrimgunduz** [anayrat/pg_sampletolog#4]
Hi @anayrat 

Do you still maintain this extension? It does not build against PostgreSQL 13+.

Regards, Devrim

**Comment by anayrat** [comment]
All these features are available since pg12 https://github.com/anayrat/pg_sampletolog/issues/3#issuecomment-925037731

**Comment by devrimgunduz** [comment]
I feel stupid (again) :(
